name: Custom Runner Workflow
on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a test
        run: |
          echo "Running on my custom runner!"
          echo "Host: $HOSTNAME"
          pwd
